### ISSUE TITLE
FTL crashes when activating DHCP server

### ISSUE THREAD

**Issue by averello** [pi-hole/FTL#1954]
### Versions
  Pi-hole version is v5.18.2 (Latest: v5.18.2)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.1 (Latest: v5.25.2)

### Platform

- OS and version: Debian GNU/Linux 12 (bookworm)  

- Platform:  Raspberry Pi 5
- Kernel: Linux 6.6.28+rpt-rpi-2712

### Expected behavior

DHCP server to be activated.

### Actual behavior / bug

FTL crashed.

### Steps to reproduce

1. Go to Settings
2. Click on DHCP tab
3. Check 'DHCP server enabled'

## Debug Token

- URL:  https://tricorder.pi-hole.net/oXIkBr9p/

### Screenshots

N/A

### Additional context

The file `/etc/dnsmasq.d/02-pihole-dhcp.conf` does not exist. I do not know if it is auto-generated.

Sysyem logs:
May 10 13:38:31 pietran pihole-FTL[9794]: dnsmasq: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran dnsmasq[9794]: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran dnsmasq[9794]: FAILED to start up
May 10 13:38:31 pietran dnsmasq[9794]: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran dnsmasq[9794]: FAILED to start up
May 10 13:38:31 pietran dnsmasq[9794]: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran dnsmasq[9794]: FAILED to start up
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] Using log file /var/log/pihole/FTL.log
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] ########## FTL started on pietran! ##########
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] FTL branch: master
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] FTL version: v5.25.1
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] FTL commit: 1c2257be
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] FTL date: 2024-02-20 20:02:36 +0100
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] FTL user: pihole
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] Compiled for aarch64 (compiled on CI) using aarch64-linux-gnu-gcc (Debian 8.3.0-2) 8.3.0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    SOCKET_LISTENING: only local
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    AAAA_QUERY_ANALYSIS: Show AAAA queries
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    MAXDBDAYS: max age for stored queries is 365 days
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    RESOLVE_IPV6: Resolve IPv6 addresses
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    RESOLVE_IPV4: Resolve IPv4 addresses
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    DBINTERVAL: saving to DB file every minute
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    DBFILE: Using /etc/pihole/pihole-FTL.db
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    MAXLOGAGE: Importing up to 24.0 hours of log data
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    PRIVACYLEVEL: Set to 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    IGNORE_LOCALHOST: Show queries from localhost
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    BLOCKINGMODE: Null IPs for blocked domains
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    ANALYZE_ONLY_A_AND_AAAA: Disabled. Analyzing all queries
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    DBIMPORT: Importing history from database
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    PIDFILE: Using /run/pihole-FTL.pid
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    SOCKETFILE: Using /run/pihole/FTL.sock
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    MACVENDORDB: Using /etc/pihole/macvendor.db
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    GRAVITYDB: Using /etc/pihole/gravity.db
May 10 13:38:31 pietran dnsmasq[9794]: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    PARSE_ARP_CACHE: Active
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    CNAME_DEEP_INSPECT: Active
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    DELAY_STARTUP: No delay requested.
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    BLOCK_ESNI: Enabled, blocking _esni.{blocked domain}
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    NICE: Set process niceness to -10 (default)
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    MAXNETAGE: Removing IP addresses and host names from network table after 365 days
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    NAMES_FROM_NETDB: Enabled, trying to get names from network database
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    EDNS0_ECS: Overwrite client from ECS information
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    REFRESH_HOSTNAMES: Periodically refreshing IPv4 names
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    RATE_LIMIT: Rate-limiting client making more than 1000 queries in 60 seconds
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    LOCAL_IPV4: Automatic interface-dependent detection of address
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    LOCAL_IPV6: Automatic interface-dependent detection of address
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    BLOCK_IPV4: Automatic interface-dependent detection of address
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    BLOCK_IPV6: Automatic interface-dependent detection of address
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    SHOW_DNSSEC: Enabled, showing automatically generated DNSSEC queries
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    MOZILLA_CANARY: Enabled
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    PIHOLE_PTR: internal PTR generation enabled (pi.hole)
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    ADDR2LINE: Enabled
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    REPLY_WHEN_BUSY: Drop queries when the database is busy
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    BLOCK_TTL: 2 seconds
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    BLOCK_ICLOUD_PR: Enabled
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    CHECK_LOAD: Enabled
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    CHECK_SHMEM: Warning if shared-memory usage exceeds 90%
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M]    CHECK_DISK: Warning if certain disk usage exceeds 90%
May 10 13:38:31 pietran dnsmasq[9794]: FAILED to start up
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] Finished config file parsing
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] Creating mutex
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.097 9794M] Creating mutex
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] PID of FTL process: 9794
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] SQLite3 message: database corruption at line 72084 of [831d0fb283] (11)
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] SQLite3 message: database disk image is malformed in "SELECT VALUE FROM ftl WHERE id = 0;" (11)
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] Encountered prepare error in db_query_int("SELECT VALUE FROM ftl WHERE id = 0;"): database disk image is malformed
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] WARN: Database /etc/pihole/pihole-FTL.db is damaged and cannot be used.
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] Database version is -2
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] Updating long-term database to version 2
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] ERROR: create_counter_table() failed!
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] Counter table not initialized, database not available
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M]  -> Total DNS queries: 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M]  -> Cached DNS queries: 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M]  -> Forwarded DNS queries: 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M]  -> Blocked DNS queries: 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M]  -> Unknown DNS queries: 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M]  -> Unique domains: 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M]  -> Unique clients: 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M]  -> Known forward destinations: 0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] Successfully accessed setupVars.conf
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.098 9794M] FATAL ERROR in dnsmasq core: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] ########## FTL terminated after 1ms  (code 1)! ##########
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FATAL ERROR in dnsmasq core: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-lock) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-strings) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-counters) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-domains) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-clients) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-queries) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-upstreams) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-overTime) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-settings) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-dns-cache) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-per-client-regex) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] ########## FTL terminated after 1ms  (code 1)! ##########
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FATAL ERROR in dnsmasq core: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-lock) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-strings) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-counters) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-domains) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-clients) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-queries) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-upstreams) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-overTime) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-settings) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:
May 10 13:38:31 pietran pihole-FTL[9794]: 38:31.099 9794M] delete_shm(): shm_unlink(FTL-dns-cache) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-per-client-regex) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] ########## FTL terminated after 2ms  (code 1)! ##########
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FATAL ERROR in dnsmasq core: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-lock) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-strings) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-counters) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-domains) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-clients) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-queries) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-upstreams) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-overTime) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-settings) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-dns-cache) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] delete_shm(): shm_unlink(FTL-per-client-regex) failed: No such file or directory
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] ########## FTL terminated after 2ms  (code 1)! ##########
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] ---------------------------->  FTL crashed!  <----------------------------
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] Please report a bug at https://github.com/pi-hole/FTL/issues
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] and include in your report already the following details:
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FTL has been running for 0 seconds
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FTL branch: master
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FTL version: v5.25.1
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FTL commit: 1c2257be
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FTL date: 2024-02-20 20:02:36 +0100
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] FTL user: started as pihole, ended as pihole
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] Compiled for aarch64 (compiled on CI) using aarch64-linux-gnu-gcc (Debian 8.3.0-2) 8.3.0
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] Process details: MID: -1
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M]                  PID: 9794
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M]                  TID: 9794
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M]                  Name: pihole-FTL
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M] Received signal: Segmentation fault
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M]      at address: 0x555649f00dd8
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.099 9794M]      with code:  SEGV_MAPERR (Address not mapped to object)
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.100 9794M] Backtrace:
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.100 9794M] B[0000]: /usr/bin/pihole-FTL(generate_backtrace+0x38) [0x555649bebec0]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.110 9794M] L[0000]: /__w/FTL/FTL/src/signals.c:98
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.111 9794M] B[0001]: /usr/bin/pihole-FTL(+0x5c394) [0x555649bec394]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.120 9794M] L[0001]: /__w/FTL/FTL/src/signals.c:242
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.121 9794M] B[0002]: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7fff3aee47b0]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.121 9794M] B[0003]: /usr/bin/pihole-FTL(die+0x8c) [0x555649c289cc]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.135 9794M] L[0003]: /__w/FTL/FTL/src/dnsmasq/log.c:503
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.135 9794M] B[0004]: /usr/bin/pihole-FTL(+0xa80d8) [0x555649c380d8]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.152 9794M] L[0004]: /__w/FTL/FTL/src/dnsmasq/option.c:5533
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.153 9794M] B[0005]: /usr/bin/pihole-FTL(+0xa82b4) [0x555649c382b4]
May 10 13:38:31 pietran systemd[1]: pihole-FTL.service: Main process exited, code=exited, status=1/FAILURE
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.171 9794M] L[0005]: /__w/FTL/FTL/src/dnsmasq/option.c:5609
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.171 9794M] B[0006]: /usr/bin/pihole-FTL(+0xa4168) [0x555649c34168]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.188 9794M] L[0006]: /__w/FTL/FTL/src/dnsmasq/option.c:2164
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.189 9794M] B[0007]: /usr/bin/pihole-FTL(+0xa7e94) [0x555649c37e94]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.207 9794M] L[0007]: /__w/FTL/FTL/src/dnsmasq/option.c:5501
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.207 9794M] B[0008]: /usr/bin/pihole-FTL(+0xa82b4) [0x555649c382b4]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.223 9794M] L[0008]: /__w/FTL/FTL/src/dnsmasq/option.c:5609
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.225 9794M] B[0009]: /usr/bin/pihole-FTL(read_opts+0xedc) [0x555649c39a44]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.241 9794M] L[0009]: /__w/FTL/FTL/src/dnsmasq/option.c:5999
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.242 9794M] B[0010]: /usr/bin/pihole-FTL(main_dnsmasq+0x108) [0x555649c11ed0]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.255 9794M] L[0010]: /__w/FTL/FTL/src/dnsmasq/dnsmasq.c:115
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.256 9794M] B[0011]: /usr/bin/pihole-FTL(main+0x100) [0x555649bd2560]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.265 9794M] L[0011]: /__w/FTL/FTL/src/main.c:118
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.265 9794M] B[0012]: /lib/aarch64-linux-gnu/libc.so.6(+0x27780) [0x7fff3ac07780]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.265 9794M] B[0013]: /lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98) [0x7fff3ac07858]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.265 9794M] B[0014]: /usr/bin/pihole-FTL(+0x42a28) [0x555649bd2a28]
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.284 9794M] L[0014]: ??:?
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] ------ Listing content of directory /dev/shm ------
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] File Mode User:Group      Size  Filename
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] rwxrwxrwx root:root        60  .
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] rwxr-xr-x root:root         5K  ..
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] rw-r--r-- plex:plex        32  9334581e-7251-4ef7-a8ec-5bfe8e89ff68
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] ---------------------------------------------------
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] Please also include some lines from above the !!!!!!!!! header.
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] Thank you for helping us to improve our FTL engine!
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] Asking parent pihole-FTL (PID -1) to shut down
May 10 13:38:31 pietran pihole-FTL[9794]: [2024-05-10 13:38:31.286 9794M] FTL fork terminated!

**Comment by DL6ER** [comment]
You are still using v5.25.1. Please update your Pi-hole.

We released [FTL v5.25.2](https://github.com/pi-hole/FTL/releases/tag/v5.25.2) two days ago. It fixes exactly what you are observing here: An invalid configuration

> ` May 10 13:38:31 pietran pihole-FTL[9794]: dnsmasq: bad dhcp-range at line 17 of /etc/dnsmasq.d/02-pihole-dhcp.conf`

causing the entire application to crash instead of properly terminating instead.

**Comment by averello** [comment]
Thank you for the fast response.
I have updated to the latest version and I still have the problem:

  Pi-hole version is v5.18.2 (Latest: v5.18.2)
  web version is v5.21 (Latest: v5.21)
  FTL version is v5.25.2 (Latest: v5.25.2)


- URL: https://tricorder.pi-hole.net/Y31OdiQv/

**Comment by DL6ER** [comment]
As the warning says, you have selected an invalid DHCP range. This is expected to prevent FTL from starting.

**Comment by averello** [comment]
Is that range specified in `/etc/dnsmasq.d/02-pihole-dhcp.conf` or in the web interface?
The `02-pihole-dhcp.conf` file does not exist on my filesystem.
Is it a generated file containing the web interface values?

**Comment by DL6ER** [comment]
> Is it a generated file containing the web interface values?

Yes, changes on the web interface recreate this file with your settings. Disabling the DHCP server deletes it IIRC
