### ISSUE TITLE
FTL does not start anymore 

### ISSUE THREAD

**Issue by bondskin** [pi-hole/FTL#743]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [] The issue I am reporting isn't a duplicate 

**How familiar are you with the codebase?:**

_1
---

**[BUG | ISSUE] Expected Behaviour:**
starting of pihole v5 does not work

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**Log file output [if available]**

[2020-05-02 16:36:14.943 6309] SQLite3 message: no such table: domain_audit in "SELECT EXISTS(SELECT domain, CASE WHEN substr(domain, 1, 1) = '*' THEN '*' || substr(:input, - length(domain) + 1) ELSE :input END matcher FROM domain_audit WHERE matcher = doma (1)
[2020-05-02 16:36:14.943 6309] gravityDB_open("SELECT EXISTS(... domain_audit ...)") - SQL error prepare: SQL logic error
[2020-05-02 16:36:14.943 6309] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-02 16:36:14.943 6309] ---------------------------->  FTL crashed!  <----------------------------
[2020-05-02 16:36:14.943 6309] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-02 16:36:14.943 6309] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-05-02 16:36:14.943 6309] and include in your report already the following details:
[2020-05-02 16:36:14.943 6309] FTL has been running for 0 seconds
[2020-05-02 16:36:14.943 6309] FTL branch: release/v5.0
[2020-05-02 16:36:14.943 6309] FTL version: vDev-5b0cfb5
[2020-05-02 16:36:14.943 6309] FTL commit: 5b0cfb5
[2020-05-02 16:36:14.944 6309] FTL date: 2020-04-28 21:05:08 +0200
[2020-05-02 16:36:14.944 6309] FTL user: started as pihole, ended as pihole
[2020-05-02 16:36:14.944 6309] Compiled for armhf (compiled on CI) using arm-linux-gnueabihf-gcc (Debian 6.3.0-18) 6.3.0 20170516
[2020-05-02 16:36:14.944 6309] Received signal: Segmentation fault
[2020-05-02 16:36:14.944 6309]      at address: 0x8
[2020-05-02 16:36:14.944 6309]      with code: SEGV_MAPERR (Address not mapped to object)
[2020-05-02 16:36:14.944 6309] Backtrace:
[2020-05-02 16:36:14.944 6309] B[0000]: 0x4f7928, /usr/bin/pihole-FTL(+0x23928) [0x4f7928]
[2020-05-02 16:36:14.944 6309] B[0001]: 0xb6d95130, /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6d95130]
[2020-05-02 16:36:14.944 6309] B[0002]: 0x4f0e54, /usr/bin/pihole-FTL(+0x1ce54) [0x4f0e54]
[2020-05-02 16:36:14.944 6309] B[0003]: 0x4f1062, /usr/bin/pihole-FTL(+0x1d062) [0x4f1062]
[2020-05-02 16:36:14.944 6309] B[0004]: 0x4f16f2, /usr/bin/pihole-FTL(gravityDB_open+0x2d) [0x4f16f2]
[2020-05-02 16:36:14.944 6309] B[0005]: 0x4f77d2, /usr/bin/pihole-FTL(FTL_reload_all_domainlists+0x11) [0x4f77d2]
[2020-05-02 16:36:14.944 6309] B[0006]: 0x4fb9a4, /usr/bin/pihole-FTL(FTL_dnsmasq_reload+0xe7) [0x4fb9a4]
[2020-05-02 16:36:14.944 6309] B[0007]: 0x51c168, /usr/bin/pihole-FTL(clear_cache_and_reload+0x17) [0x51c168]
[2020-05-02 16:36:14.944 6309] B[0008]: 0x51d6c0, /usr/bin/pihole-FTL(main_dnsmasq+0x12cb) [0x51d6c0]
[2020-05-02 16:36:14.944 6309] B[0009]: 0x4edda8, /usr/bin/pihole-FTL(main+0xa7) [0x4edda8]
[2020-05-02 16:36:14.944 6309] B[0010]: 0xb6d7f718, /lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x10c) [0xb6d7f718]
[2020-05-02 16:36:14.945 6309] ------ Listing content of directory /dev/shm ------
[2020-05-02 16:36:14.945 6309] File Mode User:Group  Filesize Filename
[2020-05-02 16:36:14.945 6309] rwxrwxrwx root:root 280 .
[2020-05-02 16:36:14.945 6309] rwxr-xr-x root:root 4K ..
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 4K FTL-per-client-regex
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 4K FTL-dns-cache
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 29K FTL-overTime
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 229K FTL-queries
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 20K FTL-upstreams
[2020-05-02 16:36:14.945 6309] rw------- pihole:pihole 643K FTL-clients
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 66K FTL-domains
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 8K FTL-strings
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 12 FTL-settings
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 124 FTL-counters
[2020-05-02 16:36:14.946 6309] rw------- pihole:pihole 28 FTL-lock
[2020-05-02 16:36:14.946 6309] rw-r--r-- fr24:fr24 2K decoder.txt
[2020-05-02 16:36:14.946 6309] ---------------------------------------------------
[2020-05-02 16:36:14.946 6309] Thank you for helping us to improve our FTL engine!
[2020-05-02 16:36:14.946 6309] FTL terminated!

**Device specifics**

Hardware Type: Raspberry Pi
OS:

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by yubiuser** [comment]
Could you elaborate a bit more about what you did right before pihole crashed? Was it a fresh installation? Did you upgrade from v4?  Have you been running v5 for a longer time already and it crashed now spontaneously?

**Comment by bondskin** [comment]
I used pihole-cloudsync and on this (secondary) pihole pulled the config from my primary pihole via GitHub.
Most likely the config got mixed up as I did not change it from pihole v4 to v5 (both Pi's are running v5).

So I tried to uninstall pihole v5 on the secondary but it was not possible to do any DNS lookups anymore on that host.
I decided to restore a backup to get the environment up and running again.

**Comment by DL6ER** [comment]
The questions asked by @yubiuser are interesting ones and we should definitely try to figure out why the `domain_audit` list is missing for you.

> [2020-05-02 16:36:14.943 6309] SQLite3 message: **no such table: domain_audit** in "SELECT EXISTS(SELECT domain, CASE WHEN substr(domain, 1, 1) = '' THEN '' || substr(:input, - length(domain) + 1) ELSE :input END matcher FROM domain_audit WHERE matcher = doma (1)

Meanwhile, I have pushed a fix to ensure FTL isn't failing when connection to a corrupted database (corrupted as is "an essential table is missing for unknown reasons").

>  I decided to restore a backup to get the environment up and running again.

@bondskin In case you encounter this issue again, you could try whether
```
pihole checkout ftl fix/free_sqlite3_stmt_vec_NULL
```
fixes the issue for you. Still, this will leave you in a semi-working state as the essential gravity database is corrupted in your case above. Even when this fix will allow FTL to run, it will not be able to block any content.

@bondskin This may be a pihole-cloudsync issue when there are handling the data base incorrectly (if at all?). Please open an issue ticket over there and link this issue ticket from here.

**Comment by yubiuser** [comment]
> I have pushed a fix to ensure FTL isn't failing when connection to a corrupted database

I've seen that fix but for me it looks only like a first step. FTL will run but not blocking anything. Shouldn't there be a kind of repair/restoring take place immediately - or do you want the user first recognize that something went wrong and let them initialize the repair manually?

**Comment by bondskin** [comment]
thanks for the command, I tried it.
But it does still not work, no local lookup possible, DNS and FTL reports to be offline
debug token: https://tricorder.pi-hole.net/cb8wfsvzk8 

pihole checkout ftl fix/free_sqlite3_stmt_vec_NULL
 

  [✓] Branch fix/free_sqlite3_stmt_vec_NULL exists
  [✓] Downloading and Installing FTL
  [✓] Restarting pihole-FTL service...
  [✓] Enabling pihole-FTL service to start on reboot...

**Comment by bondskin** [comment]
pihole-cloudsync issue: [https://github.com/stevejenkins/pihole-cloudsync/issues/11](url)

**Comment by bondskin** [comment]
Update: I manually copied the functional gravity.db from primary pihole to the secondary host.
I re-run the "pihole checkout ftl fix/free_sqlite3_stmt_vec_NULL" command and pihole is now working again.

The size of the faulty gravity.db is 1 Byte
"-rw-r--r-- 1 root   root          1 May  3 09:55 gravity.db.bck"

the functional one:
"-rw-rw-r-- 1 pihole pihole 25034752 May  3 09:55 gravity.db"

**Comment by DL6ER** [comment]
@yubiuser Usually, one cannot repair corrupted databases. SQLite3 has strong self-healing powers. All possible automatic repairs (like a recovery from a unsuccessful write during a power-loss event) are already automatically tried when opening the database for the first time in FTL (very early during the initialization).

While we could, I don't think we should try to work around databases that are broken this way (at least one entire table is missing).

@bondskin Hmm, can you share the most recent lines of your `/var/log/pihole-FTL.log` again? The debug log shows too little information so I could see if this is still the same crash or anther one for another broken database (more likely).

Also, does `pihole -g` fix the issue for you? It should rebuild the database, however, I'm not sure to which extend it will tolerate such a porous database.

>  Error: no such table: info

Doesn't look all that good either, but I cannot say something here, as I've never used pihole-cloudsync myself nor looked at their code.

**Comment by bondskin** [comment]
@DL6ER here you go

[2020-05-03 09:52:58.585 15653] Database version is 5
[2020-05-03 09:52:58.585 15653] Database successfully initialized
[2020-05-03 09:52:58.586 15653] New upstream server: 127.0.0.1 (0/1024)
[2020-05-03 09:52:58.586 15653] New upstream server: 192.168.2.1 (1/1024)
[2020-05-03 09:52:58.590 15653] Resizing "/FTL-strings" from 4096 to 8192
[2020-05-03 09:52:58.590 15653] Imported 1238 queries from the long-term database
[2020-05-03 09:52:58.590 15653]  -> Total DNS queries: 1238
[2020-05-03 09:52:58.590 15653]  -> Cached DNS queries: 695
[2020-05-03 09:52:58.590 15653]  -> Forwarded DNS queries: 523
[2020-05-03 09:52:58.590 15653]  -> Blocked DNS queries: 20
[2020-05-03 09:52:58.590 15653]  -> Unknown DNS queries: 0
[2020-05-03 09:52:58.590 15653]  -> Unique domains: 192
[2020-05-03 09:52:58.590 15653]  -> Unique clients: 20
[2020-05-03 09:52:58.590 15653]  -> Known forward destinations: 2
[2020-05-03 09:52:58.590 15653] Successfully accessed setupVars.conf
[2020-05-03 09:52:58.595 15655] PID of FTL process: 15655
[2020-05-03 09:52:58.596 15655] Listening on port 4711 for incoming IPv4 telnet connections
[2020-05-03 09:52:58.596 15655] Listening on port 4711 for incoming IPv6 telnet connections
[2020-05-03 09:52:58.596 15655] Listening on Unix socket
[2020-05-03 09:52:58.597 15655] Reloading DNS cache
[2020-05-03 09:52:58.597 15655] Blocking status is enabled
[2020-05-03 09:52:58.598 15655] SQLite3 message: no such table: domain_audit in "SELECT EXISTS(SELECT domain, CASE WHEN substr(domain, 1, 1) = '*' THEN '*' || substr(:input, - length(domain) + 1) ELSE :input END matcher FROM domain_audit WHERE matcher = doma (1)
[2020-05-03 09:52:58.598 15655] gravityDB_open("SELECT EXISTS(... domain_audit ...)") - SQL error prepare: SQL logic error
[2020-05-03 09:52:58.598 15655] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-03 09:52:58.598 15655] ---------------------------->  FTL crashed!  <----------------------------
[2020-05-03 09:52:58.598 15655] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-03 09:52:58.598 15655] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-05-03 09:52:58.598 15655] and include in your report already the following details:
[2020-05-03 09:52:58.598 15655] FTL has been running for 0 seconds
[2020-05-03 09:52:58.598 15655] FTL branch: fix/free_sqlite3_stmt_vec_NULL
[2020-05-03 09:52:58.598 15655] FTL version: vDev-027b47e
[2020-05-03 09:52:58.598 15655] FTL commit: 027b47e
[2020-05-03 09:52:58.598 15655] FTL date: 2020-05-03 09:08:41 +0200
[2020-05-03 09:52:58.598 15655] FTL user: started as pihole, ended as pihole
[2020-05-03 09:52:58.598 15655] Compiled for armhf (compiled on CI) using arm-linux-gnueabihf-gcc (Debian 6.3.0-18) 6.3.0 20170516
[2020-05-03 09:52:58.598 15655] Received signal: Segmentation fault
[2020-05-03 09:52:58.598 15655]      at address: 0x8
[2020-05-03 09:52:58.598 15655]      with code: SEGV_MAPERR (Address not mapped to object)
[2020-05-03 09:52:58.599 15655] Backtrace:
[2020-05-03 09:52:58.599 15655] B[0000]: 0x503928, /usr/bin/pihole-FTL(+0x23928) [0x503928]
[2020-05-03 09:52:58.599 15655] B[0001]: 0xb6dc6130, /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6dc6130]
[2020-05-03 09:52:58.599 15655] B[0002]: 0x4fce54, /usr/bin/pihole-FTL(+0x1ce54) [0x4fce54]
[2020-05-03 09:52:58.599 15655] B[0003]: 0x4fd064, /usr/bin/pihole-FTL(+0x1d064) [0x4fd064]
[2020-05-03 09:52:58.599 15655] B[0004]: 0x4fd6f2, /usr/bin/pihole-FTL(gravityDB_open+0x2d) [0x4fd6f2]
[2020-05-03 09:52:58.599 15655] B[0005]: 0x5037d2, /usr/bin/pihole-FTL(FTL_reload_all_domainlists+0x11) [0x5037d2]
[2020-05-03 09:52:58.599 15655] B[0006]: 0x5079a4, /usr/bin/pihole-FTL(FTL_dnsmasq_reload+0xe7) [0x5079a4]
[2020-05-03 09:52:58.599 15655] B[0007]: 0x528170, /usr/bin/pihole-FTL(clear_cache_and_reload+0x17) [0x528170]
[2020-05-03 09:52:58.599 15655] B[0008]: 0x5296c8, /usr/bin/pihole-FTL(main_dnsmasq+0x12cb) [0x5296c8]
[2020-05-03 09:52:58.599 15655] B[0009]: 0x4f9da8, /usr/bin/pihole-FTL(main+0xa7) [0x4f9da8]
[2020-05-03 09:52:58.599 15655] B[0010]: 0xb6db0718, /lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x10c) [0xb6db0718]
[2020-05-03 09:52:58.599 15655] ------ Listing content of directory /dev/shm ------
[2020-05-03 09:52:58.599 15655] File Mode User:Group  Filesize Filename
[2020-05-03 09:52:58.599 15655] rwxrwxrwx root:root 280 .
[2020-05-03 09:52:58.600 15655] rwxr-xr-x root:root 4K ..
[2020-05-03 09:52:58.600 15655] rw------- pihole:pihole 4K FTL-per-client-regex
[2020-05-03 09:52:58.600 15655] rw------- pihole:pihole 4K FTL-dns-cache
[2020-05-03 09:52:58.600 15655] rw------- pihole:pihole 29K FTL-overTime
[2020-05-03 09:52:58.600 15655] rw------- pihole:pihole 229K FTL-queries
[2020-05-03 09:52:58.600 15655] rw------- pihole:pihole 20K FTL-upstreams
[2020-05-03 09:52:58.600 15655] rw------- pihole:pihole 643K FTL-clients
[2020-05-03 09:52:58.600 15655] rw------- pihole:pihole 66K FTL-domains
[2020-05-03 09:52:58.600 15655] rw------- pihole:pihole 8K FTL-strings
[2020-05-03 09:52:58.601 15655] rw------- pihole:pihole 12 FTL-settings
[2020-05-03 09:52:58.601 15655] rw------- pihole:pihole 124 FTL-counters
[2020-05-03 09:52:58.601 15655] rw------- pihole:pihole 28 FTL-lock
[2020-05-03 09:52:58.601 15655] rw-r--r-- fr24:fr24 2K decoder.txt
[2020-05-03 09:52:58.601 15655] ---------------------------------------------------
[2020-05-03 09:52:58.601 15655] Thank you for helping us to improve our FTL engine!
[2020-05-03 09:52:58.601 15655] FTL terminated!

**Comment by bondskin** [comment]
I did to try pihole -g but copied a healthy gravity.db from another pi (running v5) to the host, that did the trick

**Comment by DL6ER** [comment]
@bondskin If you could recreate the crashing state once again, would you add
```
DEBUG_VECTORS=true
```
to your `/etc/pihole/pihole-FTL.conf` ?

This would help a lot in trying to identify what may be causing the bug, at least, it should show why my proposed fix didn't improve the situation for you as it worked for me with the deleted `domain_audit` table locally.

You can go back to the working state afterwards, however, it would be great if you could keep your damaged `gravity.db` around or maybe even send it to us somehow for local testing.

**Comment by bondskin** [comment]
Hi @DL6ER , will do but most likely not today :-)
thanks for your swift support!

**Comment by DL6ER** [comment]
Still waiting for this file. Despite this, I pushed another small change to the fix you tried, please update your branch and check if the crash still happens with the corrupted database file.

In case the database is too large, you can trim it down for sharing
```
sudo cp /etc/pihole/gravity.db /etc/pihole/gravity_small.db
sudo sqlite3 /etc/pihole/gravity_small.db "DELETE FROM gravity; VACUUM;"
```
The file `/etc/pihole/gravity_small.db` should be much smaller now but otherwise identical.

**Comment by bondskin** [comment]
Hi @DL6ER ,
Please find attached the two files (broken db with almost zero size and the current/working db as suggested above)

I tried "pihole checkout core release/v5.0" to get an update but it did not work.
How do I get an update please?

I will produce the debug FTL log today

Mike

[Archiv.zip](https://github.com/pi-hole/FTL/files/4581757/Archiv.zip)

**Comment by bondskin** [comment]
debug FTL log with a unhealthy DB

[2020-05-05 17:37:52.552 9107] Using log file /var/log/pihole-FTL.log
[2020-05-05 17:37:52.552 9107] ########## FTL started! ##########
[2020-05-05 17:37:52.552 9107] FTL branch: fix/free_sqlite3_stmt_vec_NULL
[2020-05-05 17:37:52.552 9107] FTL version: vDev-61fd420
[2020-05-05 17:37:52.552 9107] FTL commit: 61fd420
[2020-05-05 17:37:52.552 9107] FTL date: 2020-05-03 09:08:41 +0200
[2020-05-05 17:37:52.552 9107] FTL user: pihole
[2020-05-05 17:37:52.552 9107] Compiled for armhf (compiled on CI) using arm-linux-gnueabihf-gcc (Debian 6.3.0-18) 6.3.0 20170516
[2020-05-05 17:37:52.552 9107] Starting config file parsing (/etc/pihole/pihole-FTL.conf)
[2020-05-05 17:37:52.552 9107]    SOCKET_LISTENING: only local
[2020-05-05 17:37:52.552 9107]    AAAA_QUERY_ANALYSIS: Hide AAAA queries
[2020-05-05 17:37:52.552 9107]    MAXDBDAYS: max age for stored queries is 90 days
[2020-05-05 17:37:52.552 9107]    RESOLVE_IPV6: Resolve IPv6 addresses
[2020-05-05 17:37:52.552 9107]    RESOLVE_IPV4: Resolve IPv4 addresses
[2020-05-05 17:37:52.552 9107]    DBINTERVAL: saving to DB file every 3600 seconds
[2020-05-05 17:37:52.552 9107]    DBFILE: Using /etc/pihole/pihole-FTL.db
[2020-05-05 17:37:52.552 9107]    MAXLOGAGE: Importing up to 24.0 hours of log data
[2020-05-05 17:37:52.552 9107]    PRIVACYLEVEL: Set to 0
[2020-05-05 17:37:52.552 9107]    IGNORE_LOCALHOST: Show queries from localhost
[2020-05-05 17:37:52.552 9107]    BLOCKINGMODE: Null IPs for blocked domains
[2020-05-05 17:37:52.552 9107]    ANALYZE_ONLY_A_AND_AAAA: Enabled. Analyzing only A and AAAA queries
[2020-05-05 17:37:52.552 9107]    DBIMPORT: Importing history from database
[2020-05-05 17:37:52.552 9107]    PIDFILE: Using /var/run/pihole-FTL.pid
[2020-05-05 17:37:52.553 9107]    PORTFILE: Using /var/run/pihole-FTL.port
[2020-05-05 17:37:52.553 9107]    SOCKETFILE: Using /var/run/pihole/FTL.sock
[2020-05-05 17:37:52.553 9107]    SETUPVARSFILE: Using /etc/pihole/setupVars.conf
[2020-05-05 17:37:52.553 9107]    MACVENDORDB: Using /etc/pihole/macvendor.db
[2020-05-05 17:37:52.553 9107]    GRAVITYDB: Using /etc/pihole/gravity.db
[2020-05-05 17:37:52.553 9107]    PARSE_ARP_CACHE: Active
[2020-05-05 17:37:52.553 9107]    CNAME_DEEP_INSPECT: Active
[2020-05-05 17:37:52.553 9107]    DELAY_STARTUP: No delay requested.
[2020-05-05 17:37:52.553 9107]    BLOCK_ESNI: Enabled, blocking _esni.{blocked domain}
[2020-05-05 17:37:52.553 9107] *****************************
[2020-05-05 17:37:52.553 9107] * Debugging enabled         *
[2020-05-05 17:37:52.553 9107] * DEBUG_DATABASE        NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_NETWORKING      NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_LOCKS           NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_QUERIES         NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_FLAGS           NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_SHMEM           NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_GC              NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_ARP             NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_REGEX           NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_API             NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_OVERTIME        NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_EXTBLOCKED      NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_CAPS            NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_DNSMASQ_LINES   NO  *
[2020-05-05 17:37:52.553 9107] * DEBUG_VECTORS         YES *
[2020-05-05 17:37:52.553 9107] * DEBUG_RESOLVER        NO  *
[2020-05-05 17:37:52.553 9107] *****************************
[2020-05-05 17:37:52.553 9107] Finished config file parsing
[2020-05-05 17:37:52.555 9107] Database version is 5
[2020-05-05 17:37:52.555 9107] Database successfully initialized
[2020-05-05 17:37:52.555 9107] New upstream server: 127.0.0.1 (0/1024)
[2020-05-05 17:37:52.557 9107] New upstream server: 192.168.2.1 (1/1024)
[2020-05-05 17:37:52.560 9107] Resizing "/FTL-strings" from 4096 to 8192
[2020-05-05 17:37:52.566 9107] Imported 2691 queries from the long-term database
[2020-05-05 17:37:52.566 9107]  -> Total DNS queries: 2691
[2020-05-05 17:37:52.566 9107]  -> Cached DNS queries: 1367
[2020-05-05 17:37:52.566 9107]  -> Forwarded DNS queries: 1129
[2020-05-05 17:37:52.566 9107]  -> Blocked DNS queries: 195
[2020-05-05 17:37:52.566 9107]  -> Unknown DNS queries: 0
[2020-05-05 17:37:52.566 9107]  -> Unique domains: 346
[2020-05-05 17:37:52.566 9107]  -> Unique clients: 23
[2020-05-05 17:37:52.566 9107]  -> Known forward destinations: 2
[2020-05-05 17:37:52.566 9107] Successfully accessed setupVars.conf
[2020-05-05 17:37:52.566 9107] DEBUG: argv[0] = ""
[2020-05-05 17:37:52.566 9107] DEBUG: argv[1] = "-k"
[2020-05-05 17:37:52.570 9109] PID of FTL process: 9109
[2020-05-05 17:37:52.571 9109] Listening on port 4711 for incoming IPv4 telnet connections
[2020-05-05 17:37:52.571 9109] Listening on port 4711 for incoming IPv6 telnet connections
[2020-05-05 17:37:52.571 9109] Listening on Unix socket
[2020-05-05 17:37:52.572 9109] Reloading DNS cache
[2020-05-05 17:37:52.572 9109] Blocking status is enabled
[2020-05-05 17:37:52.572 9109] *****************************
[2020-05-05 17:37:52.573 9109] * Debugging enabled         *
[2020-05-05 17:37:52.573 9109] * DEBUG_DATABASE        NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_NETWORKING      NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_LOCKS           NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_QUERIES         NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_FLAGS           NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_SHMEM           NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_GC              NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_ARP             NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_REGEX           NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_API             NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_OVERTIME        NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_EXTBLOCKED      NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_CAPS            NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_DNSMASQ_LINES   NO  *
[2020-05-05 17:37:52.573 9109] * DEBUG_VECTORS         YES *
[2020-05-05 17:37:52.573 9109] * DEBUG_RESOLVER        NO  *
[2020-05-05 17:37:52.573 9109] *****************************
[2020-05-05 17:37:52.574 9109] SQLite3 message: no such table: domain_audit in "SELECT EXISTS(SELECT domain, CASE WHEN substr(domain, 1, 1) = '*' THEN '*' || substr(:input, - length(domain) + 1) ELSE :input END matcher FROM domain_audit WHERE matcher = doma (1)
[2020-05-05 17:37:52.574 9109] gravityDB_open("SELECT EXISTS(... domain_audit ...)") - SQL error prepare: SQL logic error
[2020-05-05 17:37:52.574 9109] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-05 17:37:52.574 9109] ---------------------------->  FTL crashed!  <----------------------------
[2020-05-05 17:37:52.574 9109] !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[2020-05-05 17:37:52.574 9109] Please report a bug at https://github.com/pi-hole/FTL/issues
[2020-05-05 17:37:52.574 9109] and include in your report already the following details:
[2020-05-05 17:37:52.574 9109] FTL has been running for 0 seconds
[2020-05-05 17:37:52.574 9109] FTL branch: fix/free_sqlite3_stmt_vec_NULL
[2020-05-05 17:37:52.574 9109] FTL version: vDev-61fd420
[2020-05-05 17:37:52.574 9109] FTL commit: 61fd420
[2020-05-05 17:37:52.574 9109] FTL date: 2020-05-03 09:08:41 +0200
[2020-05-05 17:37:52.574 9109] FTL user: started as pihole, ended as pihole
[2020-05-05 17:37:52.574 9109] Compiled for armhf (compiled on CI) using arm-linux-gnueabihf-gcc (Debian 6.3.0-18) 6.3.0 20170516
[2020-05-05 17:37:52.575 9109] Received signal: Segmentation fault
[2020-05-05 17:37:52.575 9109]      at address: 0x8
[2020-05-05 17:37:52.575 9109]      with code: SEGV_MAPERR (Address not mapped to object)
[2020-05-05 17:37:52.575 9109] Backtrace:
[2020-05-05 17:37:52.576 9109] B[0000]: 0x50d928, /usr/bin/pihole-FTL(+0x23928) [0x50d928]
[2020-05-05 17:37:52.576 9109] B[0001]: 0xb6d29130, /lib/arm-linux-gnueabihf/libc.so.6(__default_rt_sa_restorer+0) [0xb6d29130]
[2020-05-05 17:37:52.576 9109] B[0002]: 0x506e54, /usr/bin/pihole-FTL(+0x1ce54) [0x506e54]
[2020-05-05 17:37:52.576 9109] B[0003]: 0x507064, /usr/bin/pihole-FTL(+0x1d064) [0x507064]
[2020-05-05 17:37:52.576 9109] B[0004]: 0x5076f2, /usr/bin/pihole-FTL(gravityDB_open+0x2d) [0x5076f2]
[2020-05-05 17:37:52.576 9109] B[0005]: 0x50d7d2, /usr/bin/pihole-FTL(FTL_reload_all_domainlists+0x11) [0x50d7d2]
[2020-05-05 17:37:52.576 9109] B[0006]: 0x5119a4, /usr/bin/pihole-FTL(FTL_dnsmasq_reload+0xe7) [0x5119a4]
[2020-05-05 17:37:52.576 9109] B[0007]: 0x532178, /usr/bin/pihole-FTL(clear_cache_and_reload+0x17) [0x532178]
[2020-05-05 17:37:52.576 9109] B[0008]: 0x5336d0, /usr/bin/pihole-FTL(main_dnsmasq+0x12cb) [0x5336d0]
[2020-05-05 17:37:52.576 9109] B[0009]: 0x503da8, /usr/bin/pihole-FTL(main+0xa7) [0x503da8]
[2020-05-05 17:37:52.576 9109] B[0010]: 0xb6d13718, /lib/arm-linux-gnueabihf/libc.so.6(__libc_start_main+0x10c) [0xb6d13718]
[2020-05-05 17:37:52.576 9109] ------ Listing content of directory /dev/shm ------
[2020-05-05 17:37:52.576 9109] File Mode User:Group  Filesize Filename
[2020-05-05 17:37:52.576 9109] rwxrwxrwx root:root 280 .
[2020-05-05 17:37:52.576 9109] rwxr-xr-x root:root 4K ..
[2020-05-05 17:37:52.576 9109] rw------- pihole:pihole 4K FTL-per-client-regex
[2020-05-05 17:37:52.576 9109] rw------- pihole:pihole 4K FTL-dns-cache
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 29K FTL-overTime
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 229K FTL-queries
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 20K FTL-upstreams
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 643K FTL-clients
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 66K FTL-domains
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 8K FTL-strings
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 12 FTL-settings
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 124 FTL-counters
[2020-05-05 17:37:52.577 9109] rw------- pihole:pihole 28 FTL-lock
[2020-05-05 17:37:52.578 9109] rw-r--r-- fr24:fr24 2K decoder.txt
[2020-05-05 17:37:52.578 9109] ---------------------------------------------------
[2020-05-05 17:37:52.578 9109] Thank you for helping us to improve our FTL engine!
[2020-05-05 17:37:52.578 9109] FTL terminated!

**Comment by DL6ER** [comment]
Thanks for providing the test file, it was very clearly broken (look at the file size!)
![Screenshot from 2020-05-05 20-44-31](https://user-images.githubusercontent.com/16748619/81105657-8b746380-8f14-11ea-9976-8472219ca544.png)
however, SQLite3 didn't detect this properly and was causing a lot of internal issues we were not correctly dealing with.

I updated my fix to catch this (unlikely but still existing) scenario as well.

**Comment by bondskin** [comment]
works like charm, many thanks!

I agree, it is a rare condition but I am glad you covered even this scenario.
